apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m7vb7hs32-nodejs
  janus-idp.io/tekton: m7vb7hs32-nodejs
  backstage.io/kubernetes-id: m7vb7hs32-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m7vb7hs32-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
